export const technicalSkills = {
  programmingLanguages: [
    'C',
    'C++',
    'C#',
    'Java',
    'JavaScript',
    'Perl',
    'PHP',
    'Python',
    'Swift',
    'Go',
    'SQL',
    'R',
    'Ruby',
  ],
  productivitySoftware: [
    'Google Suite (Docs, Sheets, Slides, Forms)',
    'Trello',
    'Slack',
    'Zapier',
    'Zoom',
    'JIRA',
    'Salesforce',
  ],
  industrySpecificSkills: {
    projectManagement: [
      'Budget planning',
      'Risk management',
      'Project planning',
      'PM tools (JIRA, Trello, Monday.com)',
      'Task management',
      'SCRUM methodology',
      'Agile methodology',
    ],
    productManagement: [
      'Product roadmaps',
      'User experience design',
      'Programming skills',
      'Product lifecycle management',
      'QA testing',
      'Requirements gathering',
    ],
    softwareDevelopment: [
      'Algorithms',
      'Applications',
      'Coding',
      'Computer programming',
      'Configuration',
      'Database management',
      'Data science',
      'Data visualization',
      'Debugging',
      'Design',
      'Documentation',
      'Implementation',
      'iOS/Android',
      'Machine learning',
      'Modeling',
      'Programming languages',
      'Security',
      'Testing',
    ],
    design: [
      'Adobe Creative apps',
      'Color theory',
      'HTML',
      'Interactive media',
      'Wireframing',
      'Photoshop',
      'Prototyping',
      'Responsive design',
      'Sketch',
      'UX research',
      'User modeling',
    ],
    marketing: [
      'Automated marketing software',
      'Content creation',
      'Content management systems (CMS)',
      'Copywriting',
      'Digital media',
      'Google Analytics',
      'Marketing analytics tools',
      'Search engine optimization (SEO)',
      'Social media platforms (Twitter, Facebook, Instagram)',
    ],
  },
};
